<a href="https://colab.research.google.com/github/AfifGandhi/PrepocessingData_DataMining_Bank/blob/main/PreprocessingDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_excel('bank.xlsx')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [5]:
print (X)


[[30 'unemployed' 'married' ... -1 0 'unknown']
 [33 'services' 'married' ... 339 4 'failure']
 [35 'management' 'single' ... 330 1 'failure']
 ...
 [57 'technician' 'married' ... -1 0 'unknown']
 [28 'blue-collar' 'married' ... 211 3 'other']
 [44 'entrepreneur' 'single' ... 249 7 'other']]


In [6]:
print (Y)

['no' 'no' 'no' ... 'no' 'no' 'no']


In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(), [1])], remainder ='passthrough')
X = np.array(ct.fit_transform(X))


In [22]:
print(X)

[[0.0 0.0 0.0 ... -1 0 'unknown']
 [0.0 0.0 0.0 ... 339 4 'failure']
 [0.0 0.0 0.0 ... 330 1 'failure']
 ...
 [0.0 0.0 0.0 ... -1 0 'unknown']
 [0.0 1.0 0.0 ... 211 3 'other']
 [0.0 0.0 1.0 ... 249 7 'other']]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)


In [9]:
print (Y)

[0 0 0 ... 0 0 0]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 1)


In [11]:
print(X_train)

[[59 'technician' 'married' ... -1 0 'unknown']
 [34 'blue-collar' 'married' ... -1 0 'unknown']
 [50 'admin.' 'married' ... -1 0 'unknown']
 ...
 [28 'services' 'single' ... -1 0 'unknown']
 [45 'blue-collar' 'married' ... -1 0 'unknown']
 [48 'technician' 'divorced' ... -1 0 'unknown']]


In [12]:
print(X_test)

[[32 'admin.' 'single' ... -1 0 'unknown']
 [46 'blue-collar' 'married' ... -1 0 'unknown']
 [50 'blue-collar' 'married' ... -1 0 'unknown']
 ...
 [21 'services' 'single' ... -1 0 'unknown']
 [29 'blue-collar' 'married' ... 342 9 'failure']
 [52 'blue-collar' 'married' ... -1 0 'unknown']]


In [14]:
print(y_train)

[0 0 0 ... 1 0 0]


In [15]:
print (y_test)

[0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 

In [26]:
print("")
print("Encoding Data Kategori")
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for i in range(X.shape[1]):
    if isinstance(X[0,i], str):
        X[:, i] = label_encoder.fit_transform(X[:, i])
print(X)


Encoding Data Kategori
[[0.0 0.0 0.0 ... -1 0 3]
 [0.0 0.0 0.0 ... 339 4 0]
 [0.0 0.0 0.0 ... 330 1 0]
 ...
 [0.0 0.0 0.0 ... -1 0 3]
 [0.0 1.0 0.0 ... 211 3 1]
 [0.0 0.0 1.0 ... 249 7 1]]
